### PR TITLE
the host lazy load public suffix info when needed

### PR DESCRIPTION
**Pull request by nyamsprod**
Lazy load public suffix list info to allow reducing relying on public suffix cache

see https://github.com/thephpleague/uri-components/pull/11#issuecomment-362548228

### CODE REVIEW

**Comment by piotrantosik** [comment]
Hi, any progress? Same issue with payum descibed by @pamil

**Comment by nyamsprod** [comment]
sorry for the delay .. I'll release a patch this week if I have time ... too much work not enought time 😢

**Comment by nyamsprod** [comment]
@piotrantosik version 1.7.1 is released 🎉

**Comment by piotrantosik** [comment]
Thanks, tested and works perfectly

**Pull request merged**
