### PR TITLE
Fixed handling of query pairs having no key

### PR DESCRIPTION
**Pull request by adriferracuti**
## Introduction

In case of pairs having no keys, the pairs are incorrectly stored. 
For example, when there is a trailing ampersand, its value is stored as an element having an empty string as key and null as value. This leads to invalid URLs, especially visible in the case of manipulations done using the merge method. 

### Describe the new/upated/fixed feature

Discard pairs having no keys.

### Backward Incompatible Changes

IMHO no.

### Targeted release version

1.2.0

### PR Impact

The public API is not affected.

### CODE REVIEW

**Comment by nyamsprod** [comment]
@adriferracuti I believe this is not a issue look at the following example:

```php
<?php
use League\Uri;

$uri = Uri\create('http://example.com?foo.bar=3&');
$new_uri = Uri\merge_query($uri, 'baz=bar');
$end_uri = Uri\remove_pairs($new_uri, ['']);
echo $uri;  //returns 'http://example.com?foo.bar=3&'
echo $new_uri;  //returns 'http://example.com?foo.bar=3&&baz=bar'
echo $end_uri; //returns 'http://example.com?foo.bar=3&baz=bar'
```

`$new_uri` **is** a valid URI with a valid query string according to RFC3986. What you want is to apply some destructive normalization to the returned URI. That's why you need the addition of `Uri\remove_pairs` to normalize your URI. but by leaving out this normalization out of the box people who do not want it won't have it apply to their URI for no reason. This is a Opt In feature no an Opt Out one. 

Hope this answer your question.

**Comment by adriferracuti** [comment]
Thanks for your time and the quick reply @nyamsprod. 
I had a look at RFC3986 before creating the PR, but I could not find any reference to this particular case, could you please link it? Thanks :)

**Comment by nyamsprod** [comment]
@adriferracuti in its basic form a query is just a string see [RF3986](https://tools.ietf.org/html/rfc3986#section-3.4) so there are no key=pair relation in it even though the RFC mention it. The general convention/consensus is to use the query string as a collection of key=value pair glue using the `=` with a separator... generally `&` but then again this is only a convention and it is not backed by the RFC. 

Knowing that, the goal of this library is to respect RFC3986 and also avoid data loss. The best way to achieve that is to preserve the query string representation. Your patch just does not dot that.

`foo=bar&&bar=baz` represents 3 key pairs just like `foo=bar&hello=world&bar=baz` does :

- `foo=bar`, with `foo` as key and `bar` as value;
- ``  with the empty string as key and `null` as value (hence no `=` is present)
- `bar=baz` with `baz` as key and `baz` as value;

Your patch normalizes the query string by removing the empty pair... so your are effectively introducing some data loss in your query string which I am against. Using the fix I provided you. You can effectively normalize your query string following your business logic by adding your own dataloss logic.

Is my explanation clearer ?

**Comment by adriferracuti** [comment]
Thanks for the explanation @nyamsprod, I agree with you, but I still have doubts about the case of `&=`. Would you still consider it valid?

**Comment by nyamsprod** [comment]
Yes of course. No data loss prevail in any case. You are confusing parsing query with extracting parameters from a query  string. The problem is that in PHP parse_str extracts data with data loss and does not properly parse the query string

**Comment by nyamsprod** [comment]
@adriferracuti After our discussion I've looked into how Javascript [URLSearchParams ](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams) normalizes the query string. So I've created a PR to make the Query object behave more like URLSearchParams but without introducing a 100% compliance because that would mean BC break.

Could you look at the PR and tell me if this is more in line with what you had in mind please ? I believe looking at the test suite for the Query object should be enough 👍 . I'll merge or update the PR if you have any remarks

**Comment by nyamsprod** [comment]
I'll close this PR in favor of #8

**Comment by adriferracuti** [comment]
Thank you very much for taking care of this @nyamsprod . As soon as I have enough time I'll review your changes :)

**Pull request closed without merging**
