### PR TITLE
Update .gitattributes

### PR DESCRIPTION
**Pull request by reedy**

### CODE REVIEW

**Comment by reedy** [comment]
Similar to https://github.com/thephpleague/uri-components/pull/53

**Comment by nyamsprod** [comment]
@reedy I have merge your PR but I am not sure I will release it for the 2.x version. The reason being that this version is now on security fix only. And your PR does not address any security fix.

**Comment by reedy** [comment]
Yeah that's understandable. If a release happens it can be included. If not, it's not the end of the world!

Thanks :)

**Comment by nyamsprod** [comment]
true hence why I still did merge it... we never know 😉

**Pull request merged**
