### PR TITLE
#26 Improve Domain Name detection Regexp

### PR DESCRIPTION
**Pull request by nyamsprod**
This PR resolve issue thephpleague/uri-src#90

### CODE REVIEW

**Comment by nyamsprod** [comment]
The patch is ready for review. 

This patch enforces hostname validation according to different RFC. The public API does not change, only the `League\Uri\Components\Host::isDomain` method is made more strict and thus the `League\Uri\Components\Domain` class is also made stricter.

The patch still leaves two special registered names as valid domain name whereas they are technically not. 

```php
<?php
use League\Uri\Components\Host;

(new Host(null))->isDomain(); // will still return true 
(new Host(''))->isDomain(); // will still return true
```

These two exceptions are kept to help with usage and to reduce BC breaking. Depending on your feedback I will add this information in the documentation to be as transparent as possible. Maybe this one may be drop during another major release 🤔 

@pawelkg , @kelunik what do you think ?

**Comment by pawelkg** [comment]
The first thing I noticed is that IDN domain will not pass isDomain() test because toUnicode() is called after test itself.
Meaby it's good idea to add isIDN() method by the way?
As I can see in 1.x branch isDomain() for null and '' return false (which is correct; see: uri-components/tests/Components/HostTest.php lines 171 and 183), so this should be consider as fix not BC breaking change.

**Comment by nyamsprod** [comment]
> The first thing I noticed is that IDN domain will not pass isDomain() test because toUnicode() is called after test itself.

@pawelkg registered name are kept internally in ascii mode the isValidDomain method is only called on the ascii form of the domain name so no issue there 😉

**Comment by nyamsprod** [comment]
> As I can see in 1.x branch isDomain() for null and '' return false (which is correct; see: uri-components/tests/Components/HostTest.php lines 171 and 183), so this should be consider as fix not BC breaking change.

Then this means more changes and documentation changes in v2 at least for the Domain object.

**Comment by nyamsprod** [comment]
PR updated by removing support for the empty string and `null` as valid domain names

**Pull request merged**
